# Generated by Django 3.2.3 on 2021-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='images'),
        ),
    ]
