# Generated by Django 3.2.3 on 2021-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
